site_name: LayeredCraft CDK Constructs
site_description: Reusable AWS CDK constructs for .NET serverless applications
site_url: https://layeredcraft.github.io/cdk-constructs/
site_author: LayeredCraft Team

# Repository
repo_name: LayeredCraft/cdk-constructs
repo_url: https://github.com/LayeredCraft/cdk-constructs
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 LayeredCraft Team

# Configuration
theme:
  name: material
  language: en
  logo: docs/assets/icon.png
  favicon: docs/assets/icon.png
  
  features:
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  # Dark/Light mode toggle
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Home: index.md
  - Constructs:
    - Lambda Function: constructs/lambda-function.md
    - Static Site: constructs/static-site.md
    - DynamoDB Table: constructs/dynamodb-table.md
  - Testing: testing/index.md
  - Examples: examples/index.md

# Social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LayeredCraft/cdk-constructs
      name: GitHub Repository
    - icon: fontawesome/solid/download
      link: https://www.nuget.org/packages/LayeredCraft.Cdk.Constructs/
      name: NuGet Package