title: LayeredCraft CDK Constructs
description: Reusable AWS CDK constructs for .NET serverless applications
baseurl: "/cdk-constructs"
url: "https://layeredcraft.github.io"

# Theme settings
show_downloads: true
google_analytics: # Add your tracking ID if needed

# Build settings
markdown: kramdown
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# GitHub repository
github_username: LayeredCraft
repository: LayeredCraft/cdk-constructs

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/