title: LayeredCraft CDK Constructs
description: Reusable AWS CDK constructs for .NET serverless applications
baseurl: "/cdk-constructs"
url: "https://layeredcraft.github.io"

# Build settings
markdown: kramdown
theme: architect
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
header_pages:
  - index.md
  - constructs/lambda-function.md
  - constructs/static-site.md
  - constructs/dynamodb-table.md
  - testing/index.md
  - examples/index.md

# GitHub repository
github_username: LayeredCraft
repository: LayeredCraft/cdk-constructs

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  constructs:
    output: true
    permalink: /:collection/:name/
  testing:
    output: true
    permalink: /:collection/:name/
  examples:
    output: true
    permalink: /:collection/:name/